# Generated by Django 4.0.4 on 2022-05-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('orders_num', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('registration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('origin_country', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('voted', models.BooleanField()),
                ('current_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tea_collection', to='blog.user')),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.user')),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('article', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('popularity', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='blog.user')),
            ],
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=5)),
                ('cvv', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='blog.user')),
            ],
        ),
    ]
