# Generated by Django 4.0.4 on 2022-05-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaitem',
            name='status',
            field=models.CharField(choices=[('SELLING', 'selling'), ('MARKETPLACE', 'marketplace')], default='MARKETPLACE', max_length=20),
        ),
    ]
