# Generated by Django 4.0.4 on 2022-05-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_teaitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaitem',
            name='in_cart_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
