# Generated by Django 4.0.4 on 2022-05-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_teaitem_in_cart_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaitem',
            name='status',
            field=models.CharField(choices=[('COLLECTION', 'in collection'), ('MARKETPLACE', 'in marketplace')], default='MARKETPLACE', max_length=20),
        ),
    ]
