# Generated by Django 4.0.4 on 2022-05-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_teaitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaitem',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tea_collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teaitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COLLECTION', 'in collection'), ('MARKETPLACE', 'in marketplace')], default='MARKETPLACE', max_length=20),
        ),
    ]
