# Generated by Django 4.0.4 on 2022-05-22 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_teaitem_current_owner_alter_teaitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drop',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drops', to=settings.AUTH_USER_MODEL),
        ),
    ]
