# Generated by Django 4.0.4 on 2022-05-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_debitcard_active_alter_drop_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
