# Generated by Django 4.0.4 on 2022-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_debitcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='cvv',
            field=models.PositiveIntegerField(max_length=3),
        ),
    ]
