# Generated by Django 4.0.4 on 2022-05-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_debitcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='cvv',
            field=models.PositiveIntegerField(),
        ),
    ]
