# Generated by Django 4.0.4 on 2022-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_debitcard_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaitem',
            name='interaction_status',
            field=models.CharField(choices=[('NULL', 'null'), ('SELL', 'to be sold'), ('BUY', 'to be bought')], default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='teaitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COLLECTION', 'in collection'), ('MARKETPLACE', 'in marketplace'), ('PROCESSED', 'in process')], default='COLLECTION', max_length=20),
        ),
    ]
