# Generated by Django 4.0.4 on 2022-05-23 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_teaitem_interaction_status_alter_teaitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaitem',
            name='previous_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_sell', to=settings.AUTH_USER_MODEL),
        ),
    ]
