# Generated by Django 4.0.4 on 2022-05-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_teaitem_previous_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
