# Generated by Django 4.0.4 on 2022-05-23 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_drop_creation_date_alter_drop_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='short_article',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='drop',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drops', to=settings.AUTH_USER_MODEL),
        ),
    ]
