# Generated by Django 4.0.4 on 2022-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_drop_short_article_alter_drop_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
