# Generated by Django 4.0.4 on 2022-05-23 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_drop_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='voted_people',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_people', to=settings.AUTH_USER_MODEL),
        ),
    ]
