# Generated by Django 4.0.4 on 2022-05-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_drop_voted_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
